export const en = {
  // CLI description
  cmdDescription:
    "Interactive CLI tool for versioning and tagging management in monorepos",
  releaseDescription: "Start the interactive tagman release wizard",

  // Uncommitted changes
  uncommittedWarning:
    "Warning: You have local uncommitted changes. Do you want to continue anyway?",
  operationCancelled: "Operation cancelled.",

  // Checkpoint
  checkpointFound:
    'An interrupted release was found in phase "{step}". Do you want to resume it?',
  checkpointRollbackPrompt:
    "Do you want to revert the local changes in package.json and CHANGELOG.md that tagman managed to make?",
  checkpointRollingBack: "Reverting files to pre-release state...",
  checkpointRollbackDone: "Rollback completed. Files reverted appropriately.",

  // Package scanning
  noValidPackages: "No valid packages found in this project.",
  bye: "Bye!",
  scanningPackages: "Scanning packages for new commits...",
  scannedPackages:
    "Scanned {total} packages. Found {found} with pending changes.",
  noNewCommits: "No new commits found in any package. Nothing to release.",

  // Step 1
  step1Message: "Step 1: Select packages to release",
  step1PkgLabel: "{name} ({count} commits)",

  // Step 2
  step2Message: "Step 2: Commits for {pkgName}",
  selectAtLeastOneCommit: "Select at least one commit.",
  selectAll: "Select All",
  deselectAll: "Deselect All",

  // Step 3
  step3Message:
    "Step 3: Version increment for {pkgName} (Current: {version})",
  bumpSuggested: "suggested",
  bumpNone: "No increment (Git Tag only: {version})",
  bumpCustom: "Define a specific version...",
  customVersionPrompt: "Enter the exact version (SemVer) for {pkgName}:",
  customVersionError: "Error: must be a valid SemVer version (e.g., 1.2.3)",

  // Step 4 — Cascade
  cascadePrompt:
    "Notice: {pkgName} is a dependency of {depName}. Do you want to also version {depName} to update its reference?",

  // Step 5 — Tags
  createTagPrompt: "Create a Git tag for {pkgName}@{version}?",
  autoGeneratedMsg: "Auto-generated message for {pkgName}",
  tagMessagePrompt: "Which message do you want to use for the tag?",
  tagMsgAuto: "Use auto-generated message",
  tagMsgAppend: "Append additional text to the auto-generated message",
  tagMsgCustom: "Write a completely new message",
  appendTextPrompt: "Additional text:",
  insertPositionPrompt: "Where do you want to insert this text?",
  insertBefore: "Before the commit list",
  insertAfter: "At the end of the message",
  customTagMsgPrompt: "New message for the tag:",

  // Execution
  confirmExecute: "All set. Proceed with writing, commits, and tags?",
  cancelledByUser: "Cancelled by user.",
  writing: "Writing changes...",
  writeError: "Error updating files.",
  writeDone: "Files updated.",
  creatingGit: "Creating git commit & tags...",
  gitDone: "Git configured.",
  releaseDone: "Release complete! Versions generated successfully.",
  errorOccurred: "Error occurred.",

  // Config errors
  configParseFailed:
    "[tagman] Failed to parse {filename}: {message}",
  configInvalid:
    "[tagman] Invalid config in {filename} — using defaults.\n{error}",
} as const;

export type TranslationKey = keyof typeof en;
