import type { TranslationKey } from "./en.js";

export const es = {
  // CLI description
  cmdDescription:
    "Herramienta CLI interactiva para la gestión de versionado y tagging en monorepos",
  releaseDescription:
    "Inicia el asistente interactivo de lanzamiento de tagman",

  // Uncommitted changes
  uncommittedWarning:
    "Advertencia: Tienes cambios locales sin commitear. ¿Deseas continuar de todas formas?",
  operationCancelled: "Operación cancelada.",

  // Checkpoint
  checkpointFound:
    'Se encontró un lanzamiento interrumpido en la fase "{step}". ¿Deseas retomarlo?',
  checkpointRollbackPrompt:
    "¿Deseas revertir los cambios locales en package.json y CHANGELOG.md que tagman alcanzó a hacer?",
  checkpointRollingBack: "Revirtiendo archivos al estado pre-release...",
  checkpointRollbackDone:
    "Rollback completado. Archivos revertidos adecuadamente.",

  // Package scanning
  noValidPackages: "No se encontraron paquetes válidos en este proyecto.",
  bye: "¡Hasta luego!",
  scanningPackages: "Escaneando paquetes en busca de nuevos commits...",
  scannedPackages:
    "Se escanearon {total} paquetes. Se encontraron {found} con cambios pendientes.",
  noNewCommits:
    "No se encontraron nuevos commits en ningún paquete. Nada que lanzar.",

  // Step 1
  step1Message: "Paso 1: Selecciona los paquetes a lanzar",
  step1PkgLabel: "{name} ({count} commits)",

  // Step 2
  step2Message: "Paso 2: Commits para {pkgName}",
  selectAtLeastOneCommit: "Selecciona al menos un commit.",
  selectAll: "Seleccionar todos",
  deselectAll: "Deseleccionar todos",

  // Step 3
  step3Message:
    "Paso 3: Incremento de versión para {pkgName} (Actual: {version})",
  bumpSuggested: "sugerido",
  bumpNone: "No incrementar (solo Git Tag: {version})",
  bumpCustom: "Definir una versión específica...",
  customVersionPrompt: "Escribe la nueva versión exacta (SemVer) para {pkgName}:",
  customVersionError:
    "Error: debe ser una versión SemVer válida (ej: 1.2.3)",

  // Step 4 — Cascade
  cascadePrompt:
    "Aviso: {pkgName} es dependencia de {depName}. ¿Deseas versionar también {depName} para actualizar su referencia?",

  // Step 5 — Tags
  createTagPrompt: "¿Crear tag de Git para {pkgName}@{version}?",
  autoGeneratedMsg: "Mensaje autogenerado para {pkgName}",
  tagMessagePrompt: "¿Qué mensaje deseas usar para el tag?",
  tagMsgAuto: "Usar el mensaje autogenerado",
  tagMsgAppend: "Agregar texto adicional al autogenerado",
  tagMsgCustom: "Escribir un mensaje completamente nuevo",
  appendTextPrompt: "Texto adicional:",
  insertPositionPrompt: "¿Dónde deseas insertar este texto?",
  insertBefore: "Antes del listado de commits",
  insertAfter: "Al final del mensaje",
  customTagMsgPrompt: "Nuevo mensaje para el tag:",

  // Execution
  confirmExecute: "Todo listo. ¿Proceder con la escritura, commits y tags?",
  cancelledByUser: "Revertido por el usuario.",
  writing: "Escribiendo cambios...",
  writeError: "Error actualizando archivos.",
  writeDone: "Archivos actualizados.",
  creatingGit: "Creando git commit & tags...",
  gitDone: "Git configurado.",
  releaseDone: "¡Lanzamiento completado! Versiones generadas correctamente.",
  errorOccurred: "Ha ocurrido un error.",

  // Config errors
  configParseFailed:
    "[tagman] Error al analizar {filename}: {message}",
  configInvalid:
    "[tagman] Configuración inválida en {filename} — usando valores por defecto.\n{error}",
} as const satisfies Record<TranslationKey, string>;
